
[shell]
program = "/bin/fish"
args = ["-l"]
[window]

opacity = 0.9

padding.x = 12
padding.y = 12

decorations = "Full"
decorations_theme_variant =  "Dark"

[font]

normal.family = "FiraCode"
bold.family = "FiraCode"
italic.family = "FiraCode"
bold_italic.family = "FiraCode"

size = 11.0

# Tip: for inspiration, look for values in the source code files of your favorite VS Code themes, and use the color picker in
# Google to test colors before setting a value, or simply using an editor such as VS Code where colors are displayed in a 
# small box when a HEX is detected by the editor.
